### PR TITLE
fixes #41

### LINKED ISSUE #41: fault of the sum of values
the most of mathematical activities is good as possible but right now i got this 
https://ibb.co/k5FwcNp
it does not look the best, adding numbers in js has its drawbacks

### PR DESCRIPTION
**Pull request by plumthedev**
it rounds numbers before render, this work perfectly and fix issue

### CODE REVIEW

**Comment by soanvig** [comment]
Thanks a lot for the help

**Comment by soanvig** [comment]
I will add you to contributors and draft patch release to npm this evening, so You can have fresh and working version

**Comment by soanvig** [comment]
NPM publish version was released @plumthedev .

Unforunately I revised your solution, and it was incorrect. It rounded to full numbers, while JSR supports floating numbers too.

There is a helper tought which round to step `roundToStep()`, so I used it instead of `Math.round`.
I led to another not-pretty "bug", but I will leave it as it is, so your issue should be fixed now.

I've added you to contributors anyway.

**Comment by plumthedev** [comment]
okay thanks, if you are not angry for this bug, I can solve some of the others that you have as part of the recompense :)

**Comment by soanvig** [comment]
Well, the library in that state is not maintained anymore (see README
disclaimer) so I see no point in you investing your time, but if you want
there is a list of issues you can help with.

Im thinking currently about version 2, with rewritten codebase.

Oh, and I'm not angry. Mistakes happen all the time :)

śr., 6 lut 2019, 18:38: Kacper Pruszynski <notifications@github.com>
napisał(a):

**Pull request merged**
