### PR TITLE
update for ES5

### PR DESCRIPTION
**Pull request by johnnyflinn**
Compile DST code to ES5 for compatibility with older browsers and create-react-app minify script.
 
see: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

### CODE REVIEW

**Comment by johnnyflinn** [comment]
Just read your contributing guide.  If your set on keeping the compiled code ES2015, I'll need to create a separate NPM package (which I REALLY don't want to do) in order for it to play nice with other build pipelines (create-react-app)

**Comment by soanvig** [comment]
I don't. It is just matter of build size. I think I'll agree on es5. Thanks
for contribution. I had a lot less time to maintain that project, but i'm
going to do something about it

wt., 15 maj 2018, 14:08 użytkownik Johnny Flinn <notifications@github.com>
napisał:

**Comment by soanvig** [comment]
I'm pushing your change into development branch.

**Comment by johnnyflinn** [comment]
Any chance this can get merged into master and version bumped?

**Comment by soanvig** [comment]
Sorry, I have really busy private days. I will do it this weekend :)

pt., 1 cze 2018, 21:36 użytkownik Johnny Flinn <notifications@github.com>
napisał:

**Comment by soanvig** [comment]
v1.1.3 was released to npm for you :)

**Comment by soanvig** [comment]
I've published v1.1.4 to npm esp for you :)

**Pull request merged**
