### PR TITLE
Add support for High DPI Displays

### PR DESCRIPTION
**Pull request by sahithyen**
This PR adds support for High DPI Displays (e.g. Retina displays).

### CODE REVIEW

**Comment by sahithyen** [comment]
You are welcome. I attached two screenshots showing the difference.

Master
retina_screen_master

Development
retina_screen_dev

I'm happy to use M&M JSR for my projects 😊

**Comment by soanvig** [comment]
OT:
I suspect You have Apple hardware.

Can You confirm it works on Safari (+ it's version?). If you want, You may make PR adding that to README (master) or You can write it here, so I can commit it.

**Comment by sahithyen** [comment]
It works on Safari (11.1). I could do more extensive tests and make a PR tomorrow if you wish so.

**Comment by soanvig** [comment]
It is not neccessary, thank you. I will add Safari 11.1 to tested and supported browsers. Just wanted to provide users with general information about support.

**Pull request merged**
