### PR TITLE
Development

### PR DESCRIPTION
**Pull request by johnnyflinn**
Adds redraw method/hack in order to set min/max values.  Needed for dynamically generated data where min / max values change.

### CODE REVIEW

**Comment by soanvig** [comment]
The issue is, as I can presume, that You cannot change min/max values after initialising JSR?

**Comment by soanvig** [comment]
What I propose is to implement refresh event, and make each module have an action prepared for that event. That makes sense to me: each module then can implement refresh method by itself. Together with refresh, config object will be passed, so that each module can do what it wants.

For now I advise you to use your own implementation. I won't include your PR, however I will today add support for refreshing state of each module (or refreshing state of whole range).

Thank you for contributing.

**Comment by johnnyflinn** [comment]
No worries.  Your implementation will be a lot more stable.  I just needed something quick.  Look forward to the update.

**Comment by soanvig** [comment]
PING: I did **big** refactor, and released new version. Inspired by You!
See v1.1.0 and https://github.com/mm-jsr/jsr#refresh
I hope it does exactly what You desired.

I tested .refresh() method only with min/max config options for now, but this should be main reason to use that anyway. If we encounter any other potential functionality of that method, we will test it :)

**Comment by soanvig** [comment]
Damn. I forgot about grid totally. I need to push hotfix!

**Comment by soanvig** [comment]
It was pretty in hurry, but v1.1.1 is released (because of npm versioning).

**Pull request closed without merging**
